- alias: Washing Machine
  trigger:
    platform: numeric_state
    entity_id: sensor.vaskemaskin_power_3
    below: 5
    for:
      minutes: 2
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 12
  action:
    - service: notify.pushover
      data:
        title: "Washy washy"
        message: "Vaskemaskinen er ferdig"

- alias: Living room temperature sensor has old data
  trigger:
    platform: numeric_state
    entity_id: sensor.time
    value_template: '{{ (now() - states.sensor.stua_temperature_2.last_updated | default(strptime("19001+0100", "%Y%f%z"))).seconds / 60 }}'
    above: 120
  action:
    - service: notify.pushover
      data:
        title: "Sensor warning"
        message: "Temperaturmåler i stua sender ikke data"

- alias: Bedroom temperature sensor has old data
  trigger:
    platform: numeric_state
    entity_id: sensor.time
    value_template: '{{ (now() - states.sensor.soverom_temperature_2.last_updated | default(strptime("19001+0100", "%Y%f%z"))).seconds / 60 }}'
    above: 120
  action:
    - service: notify.pushover
      data:
        title: "Sensor warning"
        message: "Temperaturmåler på soverommet sender ikke data"

- alias: Outside temperature sensor has old data
  trigger:
    platform: numeric_state
    entity_id: sensor.time
    value_template: '{{ (now() - states.sensor.ute_temperature_2.last_updated | default(strptime("19001+0100", "%Y%f%z"))).seconds / 60 }}'
    above: 120
  action:
    - service: notify.pushover
      data:
        title: "Sensor warning"
        message: "Temperaturmåler ute sender ikke data"

- alias: Living room temperature sensor does not send data
  trigger:
    platform: numeric_state
    entity_id: sensor.time
    value_template: '{{ (now() - states.sensor.stua_temperature_2.last_updated | default(strptime("19001+0100", "%Y%f%z"))).seconds / 60 }}'
    above: 1440
  action:
    - service: notify.pushover
      data:
        title: "Sensor ERROR"
        message: "Temperaturmåler i stua sender ikke data"

- alias: Bedroom temperature sensor does not send data
  trigger:
    platform: numeric_state
    entity_id: sensor.time
    value_template: '{{ (now() - states.sensor.soverom_temperature_2.last_updated | default(strptime("19001+0100", "%Y%f%z"))).seconds / 60 }}'
    above: 1440
  action:
    - service: notify.pushover
      data:
        title: "Sensor ERROR"
        message: "Temperaturmåler på soverommet sender ikke data"

- alias: Outside temperature sensor does not send data
  trigger:
    platform: numeric_state
    entity_id: sensor.time
    value_template: '{{ (now() - states.sensor.ute_temperature_2.last_updated | default(strptime("19001+0100", "%Y%f%z"))).seconds / 60 }}'
    above: 1440
  action:
    - service: notify.pushover
      data:
        title: "Sensor ERROR"
        message: "Temperaturmåler ute sender ikke data"

- alias: IFTTT Event
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'

- alias: Workday heaters on
  trigger:
    - platform: time
      at: '04:45:00'
    - platform: time
      at: '16:15:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: script.heaters_high

- alias: Workday heaters off
  trigger:
    - platform: time
      at: '08:20:00'
    - platform: time
      at: '23:45:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: script.heaters_low

- alias: Weekend heaters on
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
    - service: script.heaters_high

- alias: Weekend heaters off
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
    - service: script.heaters_low

- alias: Plantelys on
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.plantelys

- alias: Plantelys off
  trigger:
    platform: time
    at: '19:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.plantelys

