  - alias: Washing Machine
    trigger:
      platform: numeric_state
      entity_id: sensor.vaskemaskin_power_3
      below: 5
      for:
        minutes: 2
    condition:
      condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 0.03
    action:
      service: notify.pushover
      data:
        title: "Washy washy"
        message: "Vaskemaskinen er ferdig"

  - alias: IFTTT Event
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
    action:
      service_template: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'

  - alias: Workday heaters on
    trigger:
      - platform: time
        at: '05:30:00'
      - platform: time
        at: '16:15:00'
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    action:
      - service: script.heaters_high

  - alias: Workday heaters off
    trigger:
      - platform: time
        at: '08:20:00'
      - platform: time
        at: '23:30:00'
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    action:
      - service: script.heaters_low

  - alias: Weekend heaters on
    trigger:
      platform: time
      at: '07:00:00'
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    action:
      - service: script.heaters_high

  - alias: Weekend heaters off
    trigger:
      platform: time
      at: '23:30:00'
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    action:
      - service: script.heaters_low

